// <auto-generated />
using System;
using DTMS.Wms.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DTMS.Wms.Infrastructure.Migrations
{
    [DbContext(typeof(WmsDbContext))]
    partial class WmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("wms")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DTMS.Wms.Domain.Entities.WmsLocation", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<double?>("AccuracyMeters").HasColumnType("double precision");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<string>("DisplayName").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)");
                b.Property<int>("ExternalId").HasColumnType("integer");
                b.Property<double?>("HeightDiff").HasColumnType("double precision");
                b.Property<bool>("IsActive").HasColumnType("boolean");
                b.Property<bool>("IsStorageLocation").HasColumnType("boolean");
                b.Property<DateTime>("LastSyncedAt").HasColumnType("timestamp with time zone");
                b.Property<double?>("Latitude").HasColumnType("double precision");
                b.Property<string>("LocationCode").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
                b.Property<double?>("Longitude").HasColumnType("double precision");
                b.Property<int?>("ParentLocationId").HasColumnType("integer");
                b.Property<string>("ParentLocationCode").HasMaxLength(64).HasColumnType("character varying(64)");
                b.Property<string>("ParentLocationDisplayName").HasMaxLength(128).HasColumnType("character varying(128)");
                b.Property<Guid>("RowVersion").HasColumnType("uuid");
                b.Property<int>("Type").HasColumnType("integer");
                b.Property<string>("TypeName").HasMaxLength(32).HasColumnType("character varying(32)");
                b.Property<double?>("ZGpsHeight").HasColumnType("double precision");
                b.Property<double?>("ZTolerance").HasColumnType("double precision");

                b.HasKey("Id");
                b.HasIndex("ExternalId").IsUnique();
                b.HasIndex("IsActive");
                b.HasIndex("ParentLocationCode");

                b.ToTable("Locations", "wms");
            });
#pragma warning restore 612, 618
        }
    }
}
