// <auto-generated />
using System;
using AMR.DeliveryPlanning.Planning.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AMR.DeliveryPlanning.Planning.Infrastructure.Migrations
{
    [DbContext(typeof(PlanningDbContext))]
    partial class PlanningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("planning")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AMR.DeliveryPlanning.Planning.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedVehicleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeliveryOrderId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("DerivedFromOrders")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("EstimatedDistance")
                        .HasColumnType("double precision");

                    b.Property<double>("EstimatedDuration")
                        .HasColumnType("double precision");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PlanningTrace")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RequiredCapability")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("SlaDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalWeight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Jobs", "planning");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Planning.Domain.Entities.JobDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DependencyType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<TimeSpan?>("MinimumDwell")
                        .HasColumnType("interval");

                    b.Property<Guid>("PredecessorJobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SuccessorJobId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PredecessorJobId");

                    b.HasIndex("SuccessorJobId");

                    b.ToTable("JobDependencies", "planning");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Planning.Domain.Entities.Leg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("EstimatedCost")
                        .HasColumnType("double precision");

                    b.Property<Guid>("FromStationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("ToStationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Legs", "planning");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Planning.Domain.Entities.MilkRunStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("DwellTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("PlannedArrivalOffset")
                        .HasColumnType("interval");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("MilkRunStops", "planning");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Planning.Domain.Entities.MilkRunTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CronSchedule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("MilkRunTemplates", "planning");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Planning.Domain.Entities.Stop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpectedArrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LegId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("LegId");

                    b.ToTable("Stops", "planning");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Planning.Infrastructure.Data.Records.CostModelConfigRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BatteryBurnWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("CriticalBatteryThresholdPct")
                        .HasColumnType("double precision");

                    b.Property<double>("LowBatteryThresholdPct")
                        .HasColumnType("double precision");

                    b.Property<double>("SlaPenaltyWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("TravelDistanceWeight")
                        .HasColumnType("double precision");

                    b.Property<string>("VehicleTypeKey")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VehicleTypeKey")
                        .IsUnique()
                        .HasFilter("\"VehicleTypeKey\" IS NOT NULL");

                    b.ToTable("CostModelConfigs", "planning");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Planning.Domain.Entities.Leg", b =>
                {
                    b.HasOne("AMR.DeliveryPlanning.Planning.Domain.Entities.Job", null)
                        .WithMany("Legs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Planning.Domain.Entities.MilkRunStop", b =>
                {
                    b.HasOne("AMR.DeliveryPlanning.Planning.Domain.Entities.MilkRunTemplate", null)
                        .WithMany("Stops")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Planning.Domain.Entities.Stop", b =>
                {
                    b.HasOne("AMR.DeliveryPlanning.Planning.Domain.Entities.Leg", null)
                        .WithMany("Stops")
                        .HasForeignKey("LegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Planning.Domain.Entities.Job", b =>
                {
                    b.Navigation("Legs");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Planning.Domain.Entities.Leg", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Planning.Domain.Entities.MilkRunTemplate", b =>
                {
                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
