// <auto-generated />
using System;
using AMR.DeliveryPlanning.Facility.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AMR.DeliveryPlanning.Facility.Infrastructure.Migrations
{
    [DbContext(typeof(FacilityDbContext))]
    partial class FacilityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("facility")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AMR.DeliveryPlanning.Facility.Domain.Entities.CarrierTypeProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AMRCapability")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("MaxSlots")
                        .HasColumnType("integer");

                    b.Property<double?>("MaxWeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CarrierTypeProfiles", "facility");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Facility.Domain.Entities.FacilityResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("VendorRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("FacilityResources", "facility");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Facility.Domain.Entities.LoadUnitProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CarrierTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("HeightMm")
                        .HasColumnType("double precision");

                    b.Property<double>("LengthMm")
                        .HasColumnType("double precision");

                    b.Property<double>("MaxGrossWeightKg")
                        .HasColumnType("double precision");

                    b.Property<double>("WidthMm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CarrierTypeCode");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LoadUnitProfiles", "facility");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Facility.Domain.Entities.Map", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("MapData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VendorRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Width")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("VendorRef")
                        .IsUnique()
                        .HasFilter("\"VendorRef\" IS NOT NULL");

                    b.ToTable("Maps", "facility");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Facility.Domain.Entities.RouteEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Cost")
                        .HasColumnType("double precision");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsBidirectional")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceStationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetStationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RouteEdges", "facility");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Facility.Domain.Entities.Shelf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentStationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxSlots")
                        .HasColumnType("integer");

                    b.Property<double>("MaxWeightKg")
                        .HasColumnType("double precision");

                    b.Property<string>("Rfid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.HasIndex("Rfid")
                        .IsUnique();

                    b.ToTable("Shelves", "facility");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Facility.Domain.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Actions")
                        .HasColumnType("jsonb");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CompatibleVehicleTypes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CompatibleVehicleTypes");

                    b.Property<bool>("IsActive")
                        .IsRequired()
                        .HasDefaultValue(true)
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ManualOverrideAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManualOverrideBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ManualOverrideExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ManualOverrideOffline")
                        .IsRequired()
                        .HasDefaultValue(false)
                        .HasColumnType("boolean");

                    b.Property<string>("ManualOverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VendorRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ManualOverrideExpiresAt")
                        .HasFilter("\"ManualOverrideOffline\" = true");

                    b.HasIndex("MapId", "Code")
                        .IsUnique()
                        .HasFilter("\"Code\" IS NOT NULL");

                    b.HasIndex("MapId", "IsActive");

                    b.HasIndex("MapId", "VendorRef")
                        .IsUnique()
                        .HasFilter("\"VendorRef\" IS NOT NULL");

                    b.ToTable("Stations", "facility");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Facility.Domain.Entities.TopologyOverlay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AffectedStationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<string>("PolygonJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MapId", "ValidUntil");

                    b.ToTable("TopologyOverlays", "facility");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Facility.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeofenceAreaWkt")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<int?>("GeofenceRadiusM")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ServiceModes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ServiceModes");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("Warehouses", "facility");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Facility.Domain.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("SpeedLimit")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Zones", "facility");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Facility.Domain.Entities.Station", b =>
                {
                    b.OwnsOne("AMR.DeliveryPlanning.Facility.Domain.ValueObjects.Coordinate", "Coordinate", b1 =>
                        {
                            b1.Property<Guid>("StationId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("Theta")
                                .HasColumnType("double precision")
                                .HasColumnName("CoordinateTheta");

                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("CoordinateX");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("CoordinateY");

                            b1.HasKey("StationId");

                            b1.ToTable("Stations", "facility");

                            b1.WithOwner()
                                .HasForeignKey("StationId");
                        });

                    b.Navigation("Coordinate")
                        .IsRequired();
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Facility.Domain.Entities.Warehouse", b =>
                {
                    b.OwnsOne("AMR.DeliveryPlanning.Facility.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("WarehouseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("AddressCity");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("AddressCountry");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("AddressPostalCode");

                            b1.Property<string>("State")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("AddressState");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("AddressStreet");

                            b1.HasKey("WarehouseId");

                            b1.ToTable("Warehouses", "facility");

                            b1.WithOwner()
                                .HasForeignKey("WarehouseId");
                        });

                    b.OwnsOne("AMR.DeliveryPlanning.Facility.Domain.ValueObjects.OperatingHours", "Hours", b1 =>
                        {
                            b1.Property<Guid>("WarehouseId")
                                .HasColumnType("uuid");

                            b1.Property<TimeSpan?>("FridayClose").HasColumnType("interval").HasColumnName("HoursFridayClose");
                            b1.Property<TimeSpan?>("FridayOpen").HasColumnType("interval").HasColumnName("HoursFridayOpen");
                            b1.Property<TimeSpan?>("MondayClose").HasColumnType("interval").HasColumnName("HoursMondayClose");
                            b1.Property<TimeSpan?>("MondayOpen").HasColumnType("interval").HasColumnName("HoursMondayOpen");
                            b1.Property<TimeSpan?>("SaturdayClose").HasColumnType("interval").HasColumnName("HoursSaturdayClose");
                            b1.Property<TimeSpan?>("SaturdayOpen").HasColumnType("interval").HasColumnName("HoursSaturdayOpen");
                            b1.Property<TimeSpan?>("SundayClose").HasColumnType("interval").HasColumnName("HoursSundayClose");
                            b1.Property<TimeSpan?>("SundayOpen").HasColumnType("interval").HasColumnName("HoursSundayOpen");
                            b1.Property<TimeSpan?>("ThursdayClose").HasColumnType("interval").HasColumnName("HoursThursdayClose");
                            b1.Property<TimeSpan?>("ThursdayOpen").HasColumnType("interval").HasColumnName("HoursThursdayOpen");
                            b1.Property<TimeSpan?>("TuesdayClose").HasColumnType("interval").HasColumnName("HoursTuesdayClose");
                            b1.Property<TimeSpan?>("TuesdayOpen").HasColumnType("interval").HasColumnName("HoursTuesdayOpen");
                            b1.Property<TimeSpan?>("WednesdayClose").HasColumnType("interval").HasColumnName("HoursWednesdayClose");
                            b1.Property<TimeSpan?>("WednesdayOpen").HasColumnType("interval").HasColumnName("HoursWednesdayOpen");

                            b1.HasKey("WarehouseId");

                            b1.ToTable("Warehouses", "facility");

                            b1.WithOwner()
                                .HasForeignKey("WarehouseId");
                        });

                    b.OwnsOne("AMR.DeliveryPlanning.Facility.Domain.ValueObjects.LatLng", "Location", b1 =>
                        {
                            b1.Property<Guid>("WarehouseId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Lat")
                                .HasColumnType("double precision")
                                .HasColumnName("LocationLat");

                            b1.Property<double>("Lng")
                                .HasColumnType("double precision")
                                .HasColumnName("LocationLng");

                            b1.HasKey("WarehouseId");

                            b1.ToTable("Warehouses", "facility");

                            b1.WithOwner()
                                .HasForeignKey("WarehouseId");
                        });

                    b.OwnsOne("AMR.DeliveryPlanning.Facility.Domain.ValueObjects.ContactInfo", "PrimaryContact", b1 =>
                        {
                            b1.Property<Guid>("WarehouseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("ContactEmail");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("ContactName");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("ContactPhone");

                            b1.HasKey("WarehouseId");

                            b1.ToTable("Warehouses", "facility");

                            b1.WithOwner()
                                .HasForeignKey("WarehouseId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Hours")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("PrimaryContact");
                });
#pragma warning restore 612, 618
        }
    }
}
