// <auto-generated />
using System;
using DTMS.DeliveryOrder.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DTMS.DeliveryOrder.Infrastructure.Migrations
{
    [DbContext(typeof(DeliveryOrderDbContext))]
    [Migration("20260513032134_AddItemCargoSpecific")]
    partial class AddItemCargoSpecific
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("deliveryorder")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DTMS.DeliveryOrder.Domain.Entities.DeliveryOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CargoType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("OrderRef")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("RequestedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("DeliveryOrders", "deliveryorder");
                });

            modelBuilder.Entity("DTMS.DeliveryOrder.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeliveryOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("DropLocationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("DropStationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PickupLocationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("PickupStationId")
                        .HasColumnType("uuid");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryOrderId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Items", "deliveryorder");
                });

            modelBuilder.Entity("DTMS.DeliveryOrder.Domain.Entities.OrderAmendment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AmendedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AmendedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("DeliveryOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewSnapshot")
                        .HasColumnType("jsonb");

                    b.Property<string>("OriginalSnapshot")
                        .HasColumnType("jsonb");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryOrderId");

                    b.ToTable("OrderAmendments", "deliveryorder");
                });

            modelBuilder.Entity("DTMS.DeliveryOrder.Domain.Entities.OrderAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("DeliveryOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryOrderId");

                    b.ToTable("OrderAuditEvents", "deliveryorder");
                });

            modelBuilder.Entity("DTMS.SharedKernel.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("OutboxMessages", "deliveryorder");
                });

            modelBuilder.Entity("DTMS.DeliveryOrder.Domain.Entities.Item", b =>
                {
                    b.HasOne("DTMS.DeliveryOrder.Domain.Entities.DeliveryOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("DeliveryOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DTMS.DeliveryOrder.Domain.ValueObjects.CargoSpecific", "CargoSpecific", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DateCode")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("DateCode");

                            b1.Property<string>("InventoryNo")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("InventoryNo");

                            b1.Property<string>("PartNo")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("PartNo");

                            b1.Property<string>("Po")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Po");

                            b1.Property<string>("TraceId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("TraceId");

                            b1.Property<string>("TradingCode")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("TradingCode");

                            b1.Property<string>("Vendor")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Vendor");

                            b1.HasKey("ItemId");

                            b1.ToTable("Items", "deliveryorder");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.OwnsOne("DTMS.DeliveryOrder.Domain.ValueObjects.Dimensions", "Dimensions", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid");

                            b1.Property<double>("HeightCm")
                                .HasColumnType("double precision")
                                .HasColumnName("HeightCm");

                            b1.Property<double>("LengthCm")
                                .HasColumnType("double precision")
                                .HasColumnName("LengthCm");

                            b1.Property<double>("WidthCm")
                                .HasColumnType("double precision")
                                .HasColumnName("WidthCm");

                            b1.HasKey("ItemId");

                            b1.ToTable("Items", "deliveryorder");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.Navigation("CargoSpecific");

                    b.Navigation("Dimensions");
                });

            modelBuilder.Entity("DTMS.DeliveryOrder.Domain.Entities.DeliveryOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
