// <auto-generated />
using System;
using DTMS.DeliveryOrder.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DTMS.DeliveryOrder.Infrastructure.Migrations
{
    [DbContext(typeof(DeliveryOrderDbContext))]
    partial class DeliveryOrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("deliveryorder")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DTMS.DeliveryOrder.Domain.Entities.DeliveryOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OrderRef")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RequestedTransportMode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool?>("RequiresDropPod")
                        .HasColumnType("boolean")
                        .HasColumnName("RequiresDropPod");

                    b.Property<bool?>("RequiresPickupPod")
                        .HasColumnType("boolean")
                        .HasColumnName("RequiresPickupPod");

                    b.Property<string>("SourceSystemDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceSystemKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer");

                    b.Property<double>("TotalQuantity")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalWeightKg")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("Status");

                    b.HasIndex("SourceSystemKey", "OrderRef")
                        .IsUnique();

                    b.ToTable("DeliveryOrders", "deliveryorder");
                });

            modelBuilder.Entity("DTMS.DeliveryOrder.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("DeliveryOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DropLocationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DropLocationCode");

                    b.Property<Guid?>("DropStationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DropWarehouseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DroppedOffAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DroppedOffAt");

                    b.Property<string[]>("HandlingInstructions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("HandlingInstructions");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ItemSeq")
                        .HasColumnType("integer");

                    b.Property<string>("LoadUnitProfileCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PickupLocationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PickupLocationCode");

                    b.Property<Guid?>("PickupStationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PickupWarehouseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uuid");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("TripId")
                        .HasFilter("\"TripId\" IS NOT NULL");

                    b.HasIndex("DeliveryOrderId", "ItemId")
                        .IsUnique();

                    b.HasIndex("DeliveryOrderId", "ItemSeq")
                        .IsUnique();

                    b.ToTable("Items", "deliveryorder");
                });

            modelBuilder.Entity("DTMS.DeliveryOrder.Domain.Entities.ItemPodEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Reference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ScanType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScannedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "ScanType")
                        .IsUnique();

                    b.ToTable("ItemPodEvents", "deliveryorder");
                });

            modelBuilder.Entity("DTMS.DeliveryOrder.Domain.Entities.OrderAmendment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AmendedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AmendedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("AmendmentVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("DeliveryOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewSnapshot")
                        .HasColumnType("jsonb");

                    b.Property<string>("OriginalSnapshot")
                        .HasColumnType("jsonb");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryOrderId");

                    b.ToTable("OrderAmendments", "deliveryorder");
                });

            modelBuilder.Entity("DTMS.DeliveryOrder.Domain.Entities.OrderAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Channel")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("DeliveryOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryOrderId");

                    b.ToTable("OrderAuditEvents", "deliveryorder");
                });

            modelBuilder.Entity("DTMS.DeliveryOrder.Infrastructure.Projections.OrderActivityRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Channel")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedTripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "OccurredAt")
                        .IsDescending(false, true);

                    b.HasIndex("OrderId", "Category", "OccurredAt");

                    b.ToTable("OrderActivity", "deliveryorder");
                });

            modelBuilder.Entity("DTMS.DeliveryOrder.Infrastructure.Projections.OrderFactsRow", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FinalStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("HeldAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InProgressAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderRef")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("PartiallyCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool?>("SlaCompleteBreached")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("boolean");

                    b.Property<bool?>("SlaConfirmBreached")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("boolean");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TimeToCompleteSec")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer");

                    b.Property<int?>("TimeToConfirmSec")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer");

                    b.Property<int?>("TimeToDispatchSec")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer");

                    b.Property<double>("TotalQuantity")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalWeightKg")
                        .HasColumnType("double precision");

                    b.Property<string>("TransportMode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrderId");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("SlaConfirmBreached")
                        .HasFilter("\"SlaConfirmBreached\" = true");

                    b.HasIndex("FinalStatus", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("Priority", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("SourceSystem", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("OrderFacts", "bi");
                });

            modelBuilder.Entity("DTMS.DeliveryOrder.Infrastructure.Projections.OrderFunnelHourlyRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BucketHour")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Cancelled")
                        .HasColumnType("integer");

                    b.Property<int>("Completed")
                        .HasColumnType("integer");

                    b.Property<int>("Confirmed")
                        .HasColumnType("integer");

                    b.Property<int>("Dispatched")
                        .HasColumnType("integer");

                    b.Property<int>("Failed")
                        .HasColumnType("integer");

                    b.Property<int>("Held")
                        .HasColumnType("integer");

                    b.Property<int>("InProgress")
                        .HasColumnType("integer");

                    b.Property<int>("PartiallyCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("Rejected")
                        .HasColumnType("integer");

                    b.Property<int>("Released")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BucketHour")
                        .IsUnique();

                    b.ToTable("OrderFunnelHourly", "deliveryorder");
                });

            modelBuilder.Entity("DTMS.DeliveryOrder.Infrastructure.Projections.OrderListViewRow", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("HasActiveJob")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasFailedTrip")
                        .HasColumnType("boolean");

                    b.Property<string>("LatestJobStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("LatestTripId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OrderRef")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool?>("RequiresDropPod")
                        .HasColumnType("boolean");

                    b.Property<bool?>("RequiresPickupPod")
                        .HasColumnType("boolean");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ServiceWindowEarliestUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ServiceWindowLatestUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SourceSystemDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer");

                    b.Property<double>("TotalQuantity")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalWeightKg")
                        .HasColumnType("double precision");

                    b.Property<string>("TransportMode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrderId");

                    b.HasIndex("HasActiveJob")
                        .HasFilter("\"HasActiveJob\" = true");

                    b.HasIndex("HasFailedTrip")
                        .HasFilter("\"HasFailedTrip\" = true");

                    b.HasIndex("OrderRef");

                    b.HasIndex("Priority", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("Status", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("OrderListView", "deliveryorder");
                });

            modelBuilder.Entity("DTMS.DeliveryOrder.Infrastructure.Projections.OrderStatusHistoryRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "OccurredAt")
                        .IsDescending(false, true);

                    b.HasIndex("ToStatus", "OccurredAt");

                    b.ToTable("OrderStatusHistory", "deliveryorder");
                });

            modelBuilder.Entity("DTMS.SharedKernel.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("TraceParent")
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("NextRetryAtUtc");

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("OutboxMessages", "deliveryorder");
                });

            modelBuilder.Entity("DTMS.SharedKernel.Projection.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProjectorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectorName", "EventId")
                        .IsUnique();

                    b.ToTable("ProjectionInbox", "deliveryorder");
                });

            modelBuilder.Entity("DTMS.DeliveryOrder.Domain.Entities.DeliveryOrder", b =>
                {
                    b.OwnsOne("DTMS.DeliveryOrder.Domain.ValueObjects.ServiceWindow", "ServiceWindow", b1 =>
                        {
                            b1.Property<Guid>("DeliveryOrderId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("EarliestUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ServiceWindow_EarliestUtc");

                            b1.Property<DateTime?>("LatestUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ServiceWindow_LatestUtc");

                            b1.HasKey("DeliveryOrderId");

                            b1.ToTable("DeliveryOrders", "deliveryorder");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryOrderId");
                        });

                    b.Navigation("ServiceWindow");
                });

            modelBuilder.Entity("DTMS.DeliveryOrder.Domain.Entities.Item", b =>
                {
                    b.HasOne("DTMS.DeliveryOrder.Domain.Entities.DeliveryOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("DeliveryOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DTMS.DeliveryOrder.Domain.ValueObjects.Dimensions", "Dimensions", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid");

                            b1.Property<double>("HeightMm")
                                .HasColumnType("double precision")
                                .HasColumnName("HeightMm");

                            b1.Property<double>("LengthMm")
                                .HasColumnType("double precision")
                                .HasColumnName("LengthMm");

                            b1.Property<double>("WidthMm")
                                .HasColumnType("double precision")
                                .HasColumnName("WidthMm");

                            b1.HasKey("ItemId");

                            b1.ToTable("Items", "deliveryorder");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.OwnsOne("DTMS.DeliveryOrder.Domain.ValueObjects.HazmatInfo", "Hazmat", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ClassCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("Hazmat_ClassCode");

                            b1.Property<string>("PackingGroup")
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("Hazmat_PackingGroup");

                            b1.HasKey("ItemId");

                            b1.ToTable("Items", "deliveryorder");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.OwnsOne("DTMS.DeliveryOrder.Domain.ValueObjects.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Uom");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("Quantity");

                            b1.HasKey("ItemId");

                            b1.ToTable("Items", "deliveryorder");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.OwnsOne("DTMS.DeliveryOrder.Domain.ValueObjects.TemperatureRange", "Temperature", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("MaxC")
                                .HasColumnType("double precision")
                                .HasColumnName("Temperature_MaxC");

                            b1.Property<double?>("MinC")
                                .HasColumnType("double precision")
                                .HasColumnName("Temperature_MinC");

                            b1.HasKey("ItemId");

                            b1.ToTable("Items", "deliveryorder");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.Navigation("Dimensions");

                    b.Navigation("Hazmat");

                    b.Navigation("Quantity")
                        .IsRequired();

                    b.Navigation("Temperature");
                });

            modelBuilder.Entity("DTMS.DeliveryOrder.Domain.Entities.ItemPodEvent", b =>
                {
                    b.HasOne("DTMS.DeliveryOrder.Domain.Entities.Item", null)
                        .WithMany("PodEvents")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DTMS.DeliveryOrder.Domain.Entities.DeliveryOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DTMS.DeliveryOrder.Domain.Entities.Item", b =>
                {
                    b.Navigation("PodEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
