using DTMS.Iam.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DTMS.Iam.Infrastructure.Migrations
{
    /// <inheritdoc />
    // [Migration] + [DbContext] declared directly on the migration class
    // (instead of in a separate .Designer.cs file) so EF discovers it
    // without needing the full model snapshot generated by dotnet-ef —
    // which the .NET 10 preview tooling cannot produce. See
    // feedback_migration_manual.md for the broader manual-migration rules.
    [DbContext(typeof(IamDbContext))]
    [Migration("20260627000000_AddIamPermissions")]
    public partial class AddIamPermissions : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(name: "iam");

            migrationBuilder.CreateTable(
                name: "Permissions",
                schema: "iam",
                columns: table => new
                {
                    Code = table.Column<string>(type: "character varying(120)", maxLength: 120, nullable: false),
                    Description = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: false),
                    Module = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    CreatedAt = table.Column<System.DateTime>(type: "timestamp with time zone", nullable: false),
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Permissions", x => x.Code);
                });

            migrationBuilder.CreateTable(
                name: "RolePermissions",
                schema: "iam",
                columns: table => new
                {
                    Role = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    PermissionCode = table.Column<string>(type: "character varying(120)", maxLength: 120, nullable: false),
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RolePermissions", x => new { x.Role, x.PermissionCode });
                });

            migrationBuilder.CreateIndex(
                name: "IX_Permissions_Module",
                schema: "iam",
                table: "Permissions",
                column: "Module");

            migrationBuilder.CreateIndex(
                name: "IX_RolePermissions_Role",
                schema: "iam",
                table: "RolePermissions",
                column: "Role");

            // ── Seed: Facility module permissions ─────────────────────────
            // Covers every endpoint exposed by MapEndpoints + WarehouseEndpoints.
            // Other modules will seed their own permissions in later migrations
            // (one migration per module keeps the seed list bounded and the diff
            // easy to review).
            migrationBuilder.Sql(@"
                INSERT INTO iam.""Permissions"" (""Code"", ""Description"", ""Module"", ""CreatedAt"") VALUES
                  ('dtms:facility:map:read',              'Read facility maps',                          'Facility', now()),
                  ('dtms:facility:map:write',             'Create or update facility maps',              'Facility', now()),
                  ('dtms:facility:map:import',            'Import a map from RIOT3',                     'Facility', now()),
                  ('dtms:facility:map:sync',              'Sync stations from RIOT3 for a map',          'Facility', now()),
                  ('dtms:facility:station:read',          'Read stations',                               'Facility', now()),
                  ('dtms:facility:station:write',         'Create or update stations',                   'Facility', now()),
                  ('dtms:facility:station:force-offline', 'Force a station offline (operator override)', 'Facility', now()),
                  ('dtms:facility:warehouse:read',        'Read warehouses',                             'Facility', now()),
                  ('dtms:facility:warehouse:write',       'Create or update warehouses',                 'Facility', now()),
                  ('dtms:facility:topology-overlay:write','Create or expire topology overlays',          'Facility', now()),
                  ('dtms:facility:shelf:release',         'Release a shelf RFID lock',                   'Facility', now()),
                  ('dtms:facility:profile:read',          'Read carrier type + load unit profiles',      'Facility', now()),
                  ('dtms:facility:profile:write',         'Register carrier type + load unit profiles',  'Facility', now()),
                  ('dtms:facility:resource:write',        'Register and command facility resources',     'Facility', now())
                ON CONFLICT (""Code"") DO NOTHING;
            ");

            // ── Seed: Role → Permission mapping ───────────────────────────
            // Admin gets the dtms:* wildcard so future permissions are
            // automatically granted. Supervisor / Operator are enumerated
            // explicitly so adding a permission doesn't widen their scope
            // by accident.
            migrationBuilder.Sql(@"
                INSERT INTO iam.""RolePermissions"" (""Role"", ""PermissionCode"") VALUES
                  ('Admin',      'dtms:*'),

                  ('Supervisor', 'dtms:facility:map:read'),
                  ('Supervisor', 'dtms:facility:map:sync'),
                  ('Supervisor', 'dtms:facility:station:read'),
                  ('Supervisor', 'dtms:facility:station:force-offline'),
                  ('Supervisor', 'dtms:facility:warehouse:read'),
                  ('Supervisor', 'dtms:facility:topology-overlay:write'),
                  ('Supervisor', 'dtms:facility:shelf:release'),
                  ('Supervisor', 'dtms:facility:profile:read'),

                  ('Operator',   'dtms:facility:map:read'),
                  ('Operator',   'dtms:facility:station:read'),
                  ('Operator',   'dtms:facility:warehouse:read'),
                  ('Operator',   'dtms:facility:profile:read'),
                  ('Operator',   'dtms:facility:shelf:release')
                ON CONFLICT (""Role"", ""PermissionCode"") DO NOTHING;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "RolePermissions", schema: "iam");
            migrationBuilder.DropTable(name: "Permissions", schema: "iam");
        }
    }
}
