// <auto-generated />
using System;
using AMR.DeliveryPlanning.Dispatch.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AMR.DeliveryPlanning.Dispatch.Infrastructure.Migrations
{
    [DbContext(typeof(DispatchDbContext))]
    partial class DispatchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dispatch")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AMR.DeliveryPlanning.Dispatch.Domain.Entities.AmrTripExtension", b =>
                {
                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<string>("VendorOrderKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VendorPauseSource")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VendorVehicleKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VendorVehicleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TripId");

                    b.ToTable("AmrTripExtensions", "dispatch");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Dispatch.Domain.Entities.AmrVehicleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<string>("VendorVehicleKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VendorVehicleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TripId", "Sequence")
                        .IsUnique();

                    b.ToTable("AmrVehicleAssignments", "dispatch");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Dispatch.Domain.Entities.ExecutionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("ExecutionEvents", "dispatch");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Dispatch.Domain.Entities.ProofOfDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ScannedIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SignatureData")
                        .HasColumnType("text");

                    b.Property<Guid>("StopId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("ProofsOfDelivery", "dispatch");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Dispatch.Domain.Entities.ShelfManifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("PackageBarcodes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShelfRfid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("TripId")
                        .HasFilter("\"TripId\" IS NOT NULL");

                    b.ToTable("ShelfManifests", "dispatch");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Dispatch.Domain.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeliveryOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DropStationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DropWarehouseId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PickupStationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PickupWarehouseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PreviousAttemptId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PriorityAtDispatch")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TemplateNameAtDispatch")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UpperKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("VendorExpectedCompletionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VendorFinalSnapshot")
                        .HasColumnType("jsonb");

                    b.Property<string>("VendorRequestSnapshot")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .HasFilter("\"JobId\" != '00000000-0000-0000-0000-000000000000'");

                    b.HasIndex("PreviousAttemptId")
                        .HasFilter("\"PreviousAttemptId\" IS NOT NULL");

                    b.HasIndex("UpperKey")
                        .IsUnique();

                    b.ToTable("Trips", "dispatch");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Dispatch.Domain.Entities.TripException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("RaisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Resolution")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("TripExceptions", "dispatch");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Dispatch.Domain.Entities.TripMissionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActionType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ChangeStateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("MissionIndex")
                        .HasColumnType("integer");

                    b.Property<string>("MissionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MissionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResultCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StationName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId", "MissionIndex");

                    b.HasIndex("TripId", "MissionKey", "State")
                        .IsUnique();

                    b.ToTable("TripMissionEvents", "dispatch");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Dispatch.Domain.Entities.TripRetryEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeliveryOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NewTripId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("OriginalTripId")
                        .HasColumnType("uuid");

                    b.Property<string>("RetriedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RetryReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RetrySource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryOrderId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("OriginalTripId");

                    b.ToTable("TripRetryEvents", "dispatch");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Dispatch.Infrastructure.Projections.TripFactsRow", b =>
                {
                    b.Property<Guid>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeliveryOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FinalStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("FirstPausedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastResumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PauseCount")
                        .HasColumnType("integer");

                    b.Property<bool?>("SlaCompleteBreached")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TimeToCompleteSec")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer");

                    b.Property<int?>("TimeToStartSec")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid");

                    b.Property<string>("VendorUpperKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VendorVehicleKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TripId");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("DeliveryOrderId");

                    b.HasIndex("SlaCompleteBreached")
                        .HasFilter("\"SlaCompleteBreached\" = true");

                    b.HasIndex("FinalStatus", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("VendorUpperKey", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("VendorVehicleKey", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("TripFacts", "bi");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Dispatch.Infrastructure.Projections.TripItemsRow", b =>
                {
                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemPk")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BoundAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeliveryOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DropCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<int>("ItemSeq")
                        .HasColumnType("integer");

                    b.Property<string>("ItemStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("LastEventAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LotNo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OrderRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("OrderTransportMode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PickupCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("QuantityUom")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<double?>("QuantityValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("TripId", "ItemPk");

                    b.HasIndex("DeliveryOrderId");

                    b.HasIndex("LotNo");

                    b.HasIndex("OrderRef");

                    b.ToTable("TripItems", "dispatch");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Dispatch.Infrastructure.Projections.TripStatusHistoryRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeliveryOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryOrderId", "OccurredAt");

                    b.HasIndex("ToStatus", "OccurredAt");

                    b.HasIndex("TripId", "OccurredAt")
                        .IsDescending(false, true);

                    b.ToTable("TripStatusHistory", "dispatch");
                });

            modelBuilder.Entity("DTMS.SharedKernel.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("NextRetryAtUtc");

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("OutboxMessages", "dispatch");
                });

            modelBuilder.Entity("DTMS.SharedKernel.Projection.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProjectorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectorName", "EventId")
                        .IsUnique();

                    b.ToTable("ProjectionInbox", "dispatch");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Dispatch.Domain.Entities.AmrTripExtension", b =>
                {
                    b.HasOne("AMR.DeliveryPlanning.Dispatch.Domain.Entities.Trip", null)
                        .WithOne("AmrExtension")
                        .HasForeignKey("AMR.DeliveryPlanning.Dispatch.Domain.Entities.AmrTripExtension", "TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Dispatch.Domain.Entities.AmrVehicleAssignment", b =>
                {
                    b.HasOne("AMR.DeliveryPlanning.Dispatch.Domain.Entities.AmrTripExtension", null)
                        .WithMany("VehicleAssignments")
                        .HasForeignKey("TripId")
                        .HasPrincipalKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Dispatch.Domain.Entities.ExecutionEvent", b =>
                {
                    b.HasOne("AMR.DeliveryPlanning.Dispatch.Domain.Entities.Trip", null)
                        .WithMany("Events")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Dispatch.Domain.Entities.ProofOfDelivery", b =>
                {
                    b.HasOne("AMR.DeliveryPlanning.Dispatch.Domain.Entities.Trip", null)
                        .WithMany("ProofsOfDelivery")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Dispatch.Domain.Entities.TripException", b =>
                {
                    b.HasOne("AMR.DeliveryPlanning.Dispatch.Domain.Entities.Trip", null)
                        .WithMany("Exceptions")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Dispatch.Domain.Entities.AmrTripExtension", b =>
                {
                    b.Navigation("VehicleAssignments");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Dispatch.Domain.Entities.Trip", b =>
                {
                    b.Navigation("AmrExtension");

                    b.Navigation("Events");

                    b.Navigation("Exceptions");

                    b.Navigation("ProofsOfDelivery");
                });
#pragma warning restore 612, 618
        }
    }
}
