// <auto-generated />
using DTMS.Fleet.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DTMS.Fleet.Infrastructure.Migrations
{
    [DbContext(typeof(FleetDbContext))]
    [Migration("20260430083000_AddVendorVehicleKey")]
    partial class AddVendorVehicleKey
    {
    }
}
