// <auto-generated />
using System;
using AMR.DeliveryPlanning.Facility.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AMR.DeliveryPlanning.Facility.Infrastructure.Migrations
{
    [DbContext(typeof(FacilityDbContext))]
    [Migration("20260428142823_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("facility")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AMR.DeliveryPlanning.Facility.Domain.Entities.FacilityResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("VendorRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("FacilityResources", "facility");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Facility.Domain.Entities.Map", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("MapData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VendorRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Width")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("VendorRef")
                        .IsUnique()
                        .HasFilter("\"VendorRef\" IS NOT NULL");

                    b.ToTable("Maps", "facility");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Facility.Domain.Entities.RouteEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Cost")
                        .HasColumnType("double precision");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsBidirectional")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceStationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetStationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RouteEdges", "facility");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Facility.Domain.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompatibleVehicleTypes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CompatibleVehicleTypes");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VendorRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MapId", "VendorRef")
                        .IsUnique()
                        .HasFilter("\"VendorRef\" IS NOT NULL");

                    b.ToTable("Stations", "facility");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Facility.Domain.Entities.TopologyOverlay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AffectedStationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<string>("PolygonJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MapId", "ValidUntil");

                    b.ToTable("TopologyOverlays", "facility");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Facility.Domain.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("SpeedLimit")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Zones", "facility");
                });

            modelBuilder.Entity("AMR.DeliveryPlanning.Facility.Domain.Entities.Station", b =>
                {
                    b.OwnsOne("AMR.DeliveryPlanning.Facility.Domain.ValueObjects.Coordinate", "Coordinate", b1 =>
                        {
                            b1.Property<Guid>("StationId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("Theta")
                                .HasColumnType("double precision")
                                .HasColumnName("CoordinateTheta");

                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("CoordinateX");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("CoordinateY");

                            b1.HasKey("StationId");

                            b1.ToTable("Stations", "facility");

                            b1.WithOwner()
                                .HasForeignKey("StationId");
                        });

                    b.Navigation("Coordinate")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
