// <auto-generated />
using System;
using DTMS.Facility.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DTMS.Facility.Infrastructure.Migrations
{
    [DbContext(typeof(FacilityDbContext))]
    partial class FacilityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("facility")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DTMS.Facility.Domain.Entities.CarrierTypeProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AMRCapability")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("MaxSlots")
                        .HasColumnType("integer");

                    b.Property<double?>("MaxWeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CarrierTypeProfiles", "facility");
                });

            modelBuilder.Entity("DTMS.Facility.Domain.Entities.LoadUnitProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CarrierTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("HeightMm")
                        .HasColumnType("double precision");

                    b.Property<double>("LengthMm")
                        .HasColumnType("double precision");

                    b.Property<double>("MaxGrossWeightKg")
                        .HasColumnType("double precision");

                    b.Property<double>("WidthMm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CarrierTypeCode");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LoadUnitProfiles", "facility");
                });

            modelBuilder.Entity("DTMS.Facility.Domain.Entities.Map", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("MapData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VendorRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Width")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("VendorRef")
                        .IsUnique()
                        .HasFilter("\"VendorRef\" IS NOT NULL");

                    b.ToTable("Maps", "facility");
                });

            modelBuilder.Entity("DTMS.Facility.Domain.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Actions")
                        .HasColumnType("jsonb");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CompatibleVehicleTypes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CompatibleVehicleTypes");

                    b.Property<bool>("IsActive")
                        .IsRequired()
                        .HasDefaultValue(true)
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ManualOverrideAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManualOverrideBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ManualOverrideExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ManualOverrideOffline")
                        .IsRequired()
                        .HasDefaultValue(false)
                        .HasColumnType("boolean");

                    b.Property<string>("ManualOverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VendorRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ManualOverrideExpiresAt")
                        .HasFilter("\"ManualOverrideOffline\" = true");

                    b.HasIndex("MapId", "Code")
                        .IsUnique()
                        .HasFilter("\"Code\" IS NOT NULL");

                    b.HasIndex("MapId", "IsActive");

                    b.HasIndex("MapId", "VendorRef")
                        .IsUnique()
                        .HasFilter("\"VendorRef\" IS NOT NULL");

                    b.ToTable("Stations", "facility");
                });

            modelBuilder.Entity("DTMS.Facility.Domain.Entities.Station", b =>
                {
                    b.OwnsOne("DTMS.Facility.Domain.ValueObjects.Coordinate", "Coordinate", b1 =>
                        {
                            b1.Property<Guid>("StationId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("Theta")
                                .HasColumnType("double precision")
                                .HasColumnName("CoordinateTheta");

                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("CoordinateX");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("CoordinateY");

                            b1.HasKey("StationId");

                            b1.ToTable("Stations", "facility");

                            b1.WithOwner()
                                .HasForeignKey("StationId");
                        });

                    b.Navigation("Coordinate")
                        .IsRequired();
                });

#pragma warning restore 612, 618
        }
    }
}
