// =============================================================================
// EF MIGRATION DESIGNER FILE TEMPLATE (companion to migration file)
// =============================================================================
//
// Filename: {YYYYMMDDhhmmss}_{DescriptiveName}.Designer.cs
// Purpose: Snapshot of the EF model at THIS migration's state. EF compares the
//          previous Designer.cs to this one to determine what changed.
//
// CRITICAL:
//   - This file MUST be created alongside the migration .cs file
//   - Without dotnet-ef CLI, you must update this BY HAND or by running EF tooling
//     in a sandbox project that's compatible with the model snapshot format
//
// AUTHORING STRATEGY:
//   1. Copy the PREVIOUS migration's .Designer.cs file
//   2. Update [Migration("...")] attribute to your new MigrationId
//   3. Update class name to match your migration class
//   4. Modify BuildTargetModel() to reflect changes from THIS migration:
//      - New tables: add modelBuilder.Entity<T>(b => { ... });
//      - New columns: add b.Property<T>("Name").HasColumnType("...");
//      - New FKs: add b.HasOne<T>().WithMany().HasForeignKey("...");
//
// VERIFICATION:
//   - After creating, also update {DbContextName}ModelSnapshot.cs
//   - The current ModelSnapshot.cs and the LATEST .Designer.cs should be IDENTICAL
//     in their BuildTargetModel() output (snapshot file lacks the [Migration] attribute
//     and has different class name, but model contents match)
//
// REFERENCE:
//   See existing Designer.cs files:
//   src/Modules/Dispatch/.../Migrations/20260622030000_AddTripVendorPauseSource.Designer.cs
//
// DELETE THIS COMMENT BLOCK before committing.
// =============================================================================

// <auto-generated />
using System;
using AMR.DeliveryPlanning.{Module}.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMR.DeliveryPlanning.{Module}.Infrastructure.Migrations
{
    [DbContext(typeof({YourDbContext}))]
    [Migration("{YYYYMMDDhhmmss}_{DescriptiveName}")]
    partial class {DescriptiveName}
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")            // ← match your EF Core version
                .HasAnnotation("Relational:MaxIdentifierLength", 63); // ← Postgres limit

            // -----------------------------------------------------------------
            // COPY ENTITIES FROM PREVIOUS Designer.cs + MODIFY FOR THIS MIGRATION
            // -----------------------------------------------------------------

            modelBuilder.Entity("AMR.DeliveryPlanning.{Module}.Domain.Entities.{YourEntity}", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.ToTable("your_table", "your_schema");
            });

            // ... copy other entities from previous snapshot ...

#pragma warning restore 612, 618
        }
    }
}
